require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Starter' do
    
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'CleverTap-iOS-SDK', '3.9.1'
    
  target 'StarterTests' do
    inherit! :complete
    # Pods for testing
  end

end

